#! /usr/bin/perl -w

use strict;
use Unix::Syslog qw( :macros :subs );

sub main {
    openlog("catmail", LOG_PID, LOG_USER);
    my $fn = sprintf "/var/www/vokotest/mail/%d-%d", $$, time;
    if(not open(OUT, "> $fn")) {
	syslog(LOG_ERR, "Can't open $fn: $!");
	exit 1;
    }
    while(<STDIN>) {
	print OUT $_;
    }
    close(OUT);
    exit 0;
}
main;

