#!/bin/bash
set -x
cd /var/voko

if [ -e git-repo ];
then
  echo Updating git-repo ...
  cd git-repo
  git pull
  cd ..
else
  echo Checking out code into git-repo ...
  git clone https://github.com/vokomokum/members
fi

cp -r git-repo git-repo-tmp
rm -r git-repo-tmp/.git
rm -r git-repo-tmp/members/members/tests

cd git-repo-tmp/git-repo

echo Temporary fixups - remove templates/templates/, remove RCS directories
/usr/bin/sudo /bin/rm order/templates/templates
/usr/bin/sudo /usr/bin/find . -name RCS -type d | /usr/bin/xargs /bin/rm -rf

echo Set ownership apache:apache, premissions 775  on everything in order
/usr/bin/sudo /bin/chown -R apache:apache order
/usr/bin/sudo /bin/chmod -R 775 order

echo make template files group permissions 644
/usr/bin/sudo /usr/bin/find order/templates -type f -print0 | /usr/bin/xargs -0 /usr/bin/sudo /bin/chmod 644

echo make all directories under order/ 775
/usr/bin/sudo /usr/bin/find order -type d -print0 | xargs -0 /usr/bin/sudo /bin/chmod 775 

echo now move everything onto the test server


while [ 1 == 1 ]; do
    echo -n 'Update the test site with the git files? '
    read answer
    case $answer in 
        yes|YES)
            cd order
            /usr/bin/sudo /bin/cp -rp cgi-bin templates /var/www/vokotest/
            exit 0
            ;;
        no|NO)
             exit 0
            ;;
        *)
            echo Please answer yes or no
            ;;
    esac
done


