#!/bin/bash

cd /var/voko

# choose which app to update, default: the test app
DEST=memberstest
if [ "$1" = "production" ]; then
    DEST=members
    echo I will be updating the PRODUCTION application ...
fi

BRANCH=$2
if [ "$2" = "" ]; then
    BRANCH="master"
fi


# make sure we have latest changes
if [ -e git-repo ];
then
  echo Updating git-repo ...
  cd git-repo
  git pull
  git checkout $BRANCH
  cd ..
else
  echo Checking out code into git-repo ...
  git clone git@git.assembla.com:vokomokum.git git-repo
  git checkout $BRANCH
fi

# make ourselves a nice copy to deploy from
if [ -e git-repo ];
then
    /usr/bin/sudo rm -r git-repo-tmp
fi
cp -r git-repo git-repo-tmp
rm -r git-repo-tmp/.git
rm -r git-repo-tmp/members/members/tests

echo Set ownership apache:apache, permissions 775  on everything ...
/usr/bin/sudo /bin/chown -R apache:apache git-repo-tmp
/usr/bin/sudo /bin/chmod -R 775 git-repo-tmp

cd git-repo-tmp/members

echo make template files group permissions 644 ...
/usr/bin/sudo /usr/bin/find members/templates -type f -print0 | /usr/bin/xargs -0 /usr/bin/sudo /bin/chmod 644

echo make all directories under members/ 775 ...
/usr/bin/sudo /usr/bin/find members -type d -print0 | xargs -0 /usr/bin/sudo /bin/chmod 775 

echo "now move everything (but the .ini and .wsgi files) onto the voko server ..."
sudo cp -rp CHANGES.txt README.txt setup.* members /var/www/$DEST

cd ../..
rm -r git-repo-tmp

echo develop app ...
cd /var/www/$DEST
/usr/bin/sudo /var/www/vopy/bin/python setup.py develop 

